server:
  port: 8080

spring:
  application:
    name: event-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/event_manager
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

logging:
  level:
    root: INFO
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    path: /index.html
    #url: openapi/event-manager-openapi.yaml
    tryItOutEnabled: true
    persistAuthorization: true
    withCredentials: true

jwt:
  ttl: 86400000
  key: 'd878fede59078e89bcf10c2c5eb43d760c426035362af8caa237eda1671e14e0'

event.status.cron: 0 * * * * *

validation.messages:
  location:
    empty_location_name: "Название локации не может быть пустым"
    empty_location_address: "Адрес локации не может быть пустым"
    empty_location_capacity: "Вместительность локации не может быть пустой или меньше 5"
    location_capacity_not_enough_for_events: "Вместительность локации не может быть пустой или меньше 5"
    not_found: "Не найдена локация с id %s"
    with_events: "Нельзя удалить локацию, на которой уже есть мероприятия. id %s"
  user:
    empty_user_login: "Логин пользователя не может быть пустым"
    empty_user_password: "Пароль пользователя не может быть пустым"
    empty_user_age: "Возраст пользователя не может быть пустой или меньше 18"

    not_found_by_id: "Не найден пользователь с id %s"
    not_found_by_login: "Не найден пользователь с логином %s"
    login_taken: "Пользователь с таким логином уже существует"
  event:
    exceed_location_capacity: "Вместимость локации не соответствует мероприятию"
    date_time_overlaps: "Мероприятие пересекается по времени с другим в этой локации"
    wrong_user: "Обычные пользователи не могут изменять или отменять чужие мероприятия"
    wrong_status: "Нельзя изменять, отменять или регистрироваться на мероприятия, которые начались, завершились или уже отменены"
    wrong_new_max_places_on_update: "Нельзя установить количество мест меньше, чем уже занято"
  registration:
    admin_registration: "Админам запрещено регистрироваться на мероприятия"
    event_no_places: "На мероприятия закончились места"
    user_already_registered: "Текущий пользователь уже зарегистрирован на это мероприятие"
    absent_for_event: "У пользователя отсутствует регистрация на это мероприятие"
